services:
  - type: web
    name: tlg-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.utils.main:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
